### ISSUE TITLE
Problem set 3 exercise 3 - Class 2

### ISSUE THREAD

**Issue by xfz809** [NumEconCopenhagen/lectures-2020#4]
Hello Emil,
I've tried to run problem 3 in the exercises, but I can't load the data, I keep getting an error:
No such file or directory: 'data/NAH1_pivoted.xlsx'

I have tried to use the code in the answers :
nah1 = pd.read_excel('data/NAH1_pivoted.xlsx',skiprows=2)

I use jupyter lab and have also tried to change the "data/" with "numerical/ugesedler" which is where my data is in jupyter lab, but it doesn't help. 
I hope you can help.

**Comment by emilcphu** [comment]
Hi Frederikke,

The error you receive tells you that python cannot find the file you are trying to load.

A simple solution could be to define a new variable containing the full path to the file. For example something like this:

```
folder_path = 'C:\\Users\\pdj165\\Documents\\TA\\NumEconCopenhagen\\'
file_name   = 'NAH1_pivoted.xlsx'

df_nah1 = pd.read_excel(folder_path + file_name)
```

Please notice that I add two backslashes instead of one. You can check out why I do this, and other ways of doing it in this stackoverflow issue: https://stackoverflow.com/questions/2953834/windows-path-in-python

Let me know if this solved your problem?

**Comment by xfz809** [comment]
Yes that worked :)
Thank you!
